# Generated by Django 4.1.7 on 2023-03-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sorteio',
            new_name='Participante',
        ),
    ]
