# Generated by Django 4.1.7 on 2023-03-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio', '0002_rename_sorteio_participante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='cidade',
            new_name='estado',
        ),
    ]
